### PR TITLE
Get primary key from serializer instead of default 'id'

### PR DESCRIPTION
**Pull request by rqton**
Hi again Mike, i'm back ;)

My first PR (https://github.com/mike-north/ember-api-actions/pull/40) was to specific.
Here is a new PR much more generic.

In the `DS.JSONAPISerializer` [API](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#property_primaryKey) , you can change the primaryKey for all models or a specific model.
In your addon, when you build the URL, you choose the primaryKey 'id' instead of getting the primaryKey set in the serializer.

Of course if not primaryKey is set in the serializer, the default value is 'id' :)

### CODE REVIEW

**Comment by mike-north** [comment]
Yes! This is a much better approach, and a welcome improvement to the addon. Please add tests & documentation

**Comment by rqton** [comment]
Hi Mike,

I'm finally back. Sorry for the delay.
By saying "add tests", do you mean that I have to update the "Dummy" page with a new model to show how this feature works ?

**Comment by mike-north** [comment]
You should make a unit or acceptance test that uses ember-api-actions with a serializer whose primary key is not "id", and validate that it works as expected. This might involve using the dummy app

**Comment by rqton** [comment]
Hi Mike,

During my work on tests, i seriously doubt my PR.
The [API](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#property_primaryKey) says that ember data will always uses the `id` property to store the id of the record, so there's no reason that ember-api-actions gets another key than `id` to perform actions.
I just misunderstood how this property really works.

If we are on the same page, i will close my PR :(
Thank your for your time and your great addon.

**Comment by mike-north** [comment]
No worries :) sounds like this addon already does what you need if I understand correctly

**Comment by rqton** [comment]
Sure it does :) I'll close my PR.

**Pull request closed without merging**
