### PR TITLE
Unused Dependency & Deprecation Removal

### PR DESCRIPTION
**Pull request by alexlafroscia**
* Remove some deprecated dependencies, in some cases replacing with the non-deprecated versions
* Remove some now-unused test helpers that were left over from the "old" testing style
* Update `ember-data` to remove dependency on jQuery for running tests
  * Old `ember-data` version required jQuery
  * Updated `ember-data` warned about missing serializer, so that was added. Adapter modified for consistent with serializer.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
@Turbo87 any chance you have permissions to re-start the build on Travis? Ever since rebasing to resolve a merge conflict with #431 this morning the Travis has just been stalled out.

**Comment by Turbo87** [comment]
I probably can. Alternatively you can amend the last commit and force push :)

**Comment by alexlafroscia** [comment]
Good call, I did that instead!

**Comment by alexlafroscia** [comment]
@Turbo87 finally passing -- if you can merge this, I'd appreciate it!

**Comment by alexlafroscia** [comment]
Thanks!

**Pull request merged**
